### ISSUE TITLE
Bot is not looking for the last day of the month

### ISSUE THREAD

**Issue by 0xAaCE** [juanidambrosio/smileshelper#26]
https://github.com/juanidambrosio/smileshelper/blob/4f3bcb43ce637cbc4e83458c337e2e1baa55ddd8/clients/smilesClient.js#L154

`day <= (fixedDay ? 1 : lastDayOfMonthDeparture); `

**Comment by juanidambrosio** [comment]
The loop starts in 0, so it actually covers the last day
